input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["namedentitytopic"]
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "named-entities"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
  stdout { codec => rubydebug }
}
